AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  SuggestExtensions: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
Metrics/ClassLength:
  Max: 200
Metrics/MethodLength:
  Max: 20
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: always_inspect
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/Documentation:
  Enabled: false
Lint/EndAlignment:
  EnforcedStyleAlignWith: variable
