name: Ruby CI

on:
  push:
  pull_request:

jobs:

  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.5.8', '2.6', '2.7', '3.0', '3.1', '3.2.2']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Install dependencies
      run: bundle install --jobs 4
    - name: Run RuboCop
      run: bundle exec rubocop --config .rubocop.yml
    - name: Run RSpec + SimpleCov
      run: COVERAGE=true bundle exec rspec --format documentation